// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: nuts/echo/v1/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoServiceEchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EchoServiceEchoRequest) Reset() {
	*x = EchoServiceEchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoRequest) ProtoMessage() {}

func (x *EchoServiceEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoRequest.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoRequest) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoServiceEchoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EchoServiceEchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EchoServiceEchoResponse) Reset() {
	*x = EchoServiceEchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoResponse) ProtoMessage() {}

func (x *EchoServiceEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoResponse.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoResponse) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoServiceEchoResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EchoServiceEchoBodyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num string `protobuf:"bytes,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *EchoServiceEchoBodyRequest) Reset() {
	*x = EchoServiceEchoBodyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoBodyRequest) ProtoMessage() {}

func (x *EchoServiceEchoBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoBodyRequest.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoBodyRequest) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoServiceEchoBodyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EchoServiceEchoBodyRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

type EchoServiceEchoBodyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EchoServiceEchoBodyResponse) Reset() {
	*x = EchoServiceEchoBodyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoBodyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoBodyResponse) ProtoMessage() {}

func (x *EchoServiceEchoBodyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoBodyResponse.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoBodyResponse) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{3}
}

func (x *EchoServiceEchoBodyResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EchoServiceEchoHeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num string `protobuf:"bytes,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *EchoServiceEchoHeaderRequest) Reset() {
	*x = EchoServiceEchoHeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoHeaderRequest) ProtoMessage() {}

func (x *EchoServiceEchoHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoHeaderRequest.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoHeaderRequest) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{4}
}

func (x *EchoServiceEchoHeaderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EchoServiceEchoHeaderRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

type EchoServiceEchoHeaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EchoServiceEchoHeaderResponse) Reset() {
	*x = EchoServiceEchoHeaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoHeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoHeaderResponse) ProtoMessage() {}

func (x *EchoServiceEchoHeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoHeaderResponse.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoHeaderResponse) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{5}
}

func (x *EchoServiceEchoHeaderResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EchoServiceEchoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *EchoServiceEchoUploadRequest) Reset() {
	*x = EchoServiceEchoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoUploadRequest) ProtoMessage() {}

func (x *EchoServiceEchoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoUploadRequest.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoUploadRequest) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{6}
}

func (x *EchoServiceEchoUploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EchoServiceEchoUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type EchoServiceEchoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EchoServiceEchoUploadResponse) Reset() {
	*x = EchoServiceEchoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuts_echo_v1_echo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoServiceEchoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoServiceEchoUploadResponse) ProtoMessage() {}

func (x *EchoServiceEchoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nuts_echo_v1_echo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoServiceEchoUploadResponse.ProtoReflect.Descriptor instead.
func (*EchoServiceEchoUploadResponse) Descriptor() ([]byte, []int) {
	return file_nuts_echo_v1_echo_proto_rawDescGZIP(), []int{7}
}

func (x *EchoServiceEchoUploadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_nuts_echo_v1_echo_proto protoreflect.FileDescriptor

var file_nuts_echo_v1_echo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x75, 0x74, 0x73, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x63, 0x68, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x75, 0x74, 0x73, 0x2e,
	0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x16, 0x45, 0x63, 0x68, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x17, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x1a, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x33, 0x0a, 0x1b, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x1c, 0x45,
	0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x35, 0x0a,
	0x1d, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x1c, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x35, 0x0a, 0x1d, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x63, 0x68, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x9b, 0x03, 0x0a, 0x0b, 0x45, 0x63,
	0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x04, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x24, 0x2e, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65,
	0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x28, 0x2e, 0x6e,
	0x75, 0x74, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63,
	0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x0a, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x2a, 0x2e, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68,
	0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x0a,
	0x45, 0x63, 0x68, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x2e, 0x6e, 0x75, 0x74,
	0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63,
	0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x63, 0x68, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x86, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e,
	0x6e, 0x75, 0x74, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x45, 0x63,
	0x68, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x13, 0x6e, 0x75, 0x74, 0x73, 0x2f,
	0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x63, 0x68, 0x6f, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x4e, 0x45, 0x58, 0xaa, 0x02, 0x0c, 0x4e, 0x75, 0x74, 0x73, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x4e, 0x75, 0x74, 0x73, 0x5c, 0x45, 0x63, 0x68, 0x6f, 0x5f,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x4e, 0x75, 0x74, 0x73, 0x5c, 0x45, 0x63, 0x68, 0x6f, 0x5f,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0e, 0x4e, 0x75, 0x74, 0x73, 0x3a, 0x3a, 0x45, 0x63, 0x68, 0x6f, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nuts_echo_v1_echo_proto_rawDescOnce sync.Once
	file_nuts_echo_v1_echo_proto_rawDescData = file_nuts_echo_v1_echo_proto_rawDesc
)

func file_nuts_echo_v1_echo_proto_rawDescGZIP() []byte {
	file_nuts_echo_v1_echo_proto_rawDescOnce.Do(func() {
		file_nuts_echo_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_nuts_echo_v1_echo_proto_rawDescData)
	})
	return file_nuts_echo_v1_echo_proto_rawDescData
}

var file_nuts_echo_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nuts_echo_v1_echo_proto_goTypes = []interface{}{
	(*EchoServiceEchoRequest)(nil),        // 0: nuts.echo.v1.EchoServiceEchoRequest
	(*EchoServiceEchoResponse)(nil),       // 1: nuts.echo.v1.EchoServiceEchoResponse
	(*EchoServiceEchoBodyRequest)(nil),    // 2: nuts.echo.v1.EchoServiceEchoBodyRequest
	(*EchoServiceEchoBodyResponse)(nil),   // 3: nuts.echo.v1.EchoServiceEchoBodyResponse
	(*EchoServiceEchoHeaderRequest)(nil),  // 4: nuts.echo.v1.EchoServiceEchoHeaderRequest
	(*EchoServiceEchoHeaderResponse)(nil), // 5: nuts.echo.v1.EchoServiceEchoHeaderResponse
	(*EchoServiceEchoUploadRequest)(nil),  // 6: nuts.echo.v1.EchoServiceEchoUploadRequest
	(*EchoServiceEchoUploadResponse)(nil), // 7: nuts.echo.v1.EchoServiceEchoUploadResponse
}
var file_nuts_echo_v1_echo_proto_depIdxs = []int32{
	0, // 0: nuts.echo.v1.EchoService.Echo:input_type -> nuts.echo.v1.EchoServiceEchoRequest
	2, // 1: nuts.echo.v1.EchoService.EchoBody:input_type -> nuts.echo.v1.EchoServiceEchoBodyRequest
	4, // 2: nuts.echo.v1.EchoService.EchoHeader:input_type -> nuts.echo.v1.EchoServiceEchoHeaderRequest
	6, // 3: nuts.echo.v1.EchoService.EchoUpload:input_type -> nuts.echo.v1.EchoServiceEchoUploadRequest
	1, // 4: nuts.echo.v1.EchoService.Echo:output_type -> nuts.echo.v1.EchoServiceEchoResponse
	3, // 5: nuts.echo.v1.EchoService.EchoBody:output_type -> nuts.echo.v1.EchoServiceEchoBodyResponse
	5, // 6: nuts.echo.v1.EchoService.EchoHeader:output_type -> nuts.echo.v1.EchoServiceEchoHeaderResponse
	7, // 7: nuts.echo.v1.EchoService.EchoUpload:output_type -> nuts.echo.v1.EchoServiceEchoUploadResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nuts_echo_v1_echo_proto_init() }
func file_nuts_echo_v1_echo_proto_init() {
	if File_nuts_echo_v1_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nuts_echo_v1_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoBodyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoBodyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoHeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoHeaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuts_echo_v1_echo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoServiceEchoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nuts_echo_v1_echo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nuts_echo_v1_echo_proto_goTypes,
		DependencyIndexes: file_nuts_echo_v1_echo_proto_depIdxs,
		MessageInfos:      file_nuts_echo_v1_echo_proto_msgTypes,
	}.Build()
	File_nuts_echo_v1_echo_proto = out.File
	file_nuts_echo_v1_echo_proto_rawDesc = nil
	file_nuts_echo_v1_echo_proto_goTypes = nil
	file_nuts_echo_v1_echo_proto_depIdxs = nil
}
