// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: HI.proto

package HI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "micro.dev/v4/service/client"
	server "micro.dev/v4/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for HI service

type HIService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (HI_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (HI_PingPongService, error)
}

type hIService struct {
	c    client.Client
	name string
}

func NewHIService(name string, c client.Client) HIService {
	return &hIService{
		c:    c,
		name: name,
	}
}

func (c *hIService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "HI.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hIService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (HI_StreamService, error) {
	req := c.c.NewRequest(c.name, "HI.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hIServiceStream{stream}, nil
}

type HI_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type hIServiceStream struct {
	stream client.Stream
}

func (x *hIServiceStream) Close() error {
	return x.stream.Close()
}

func (x *hIServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hIServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hIServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hIServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hIService) PingPong(ctx context.Context, opts ...client.CallOption) (HI_PingPongService, error) {
	req := c.c.NewRequest(c.name, "HI.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &hIServicePingPong{stream}, nil
}

type HI_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type hIServicePingPong struct {
	stream client.Stream
}

func (x *hIServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *hIServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *hIServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hIServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hIServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *hIServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for HI service

type HIHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, HI_StreamStream) error
	PingPong(context.Context, HI_PingPongStream) error
}

func RegisterHIHandler(s server.Server, hdlr HIHandler, opts ...server.HandlerOption) error {
	type hI interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type HI struct {
		hI
	}
	h := &hIHandler{hdlr}
	return s.Handle(s.NewHandler(&HI{h}, opts...))
}

type hIHandler struct {
	HIHandler
}

func (h *hIHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HIHandler.Call(ctx, in, out)
}

func (h *hIHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HIHandler.Stream(ctx, m, &hIStreamStream{stream})
}

type HI_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type hIStreamStream struct {
	stream server.Stream
}

func (x *hIStreamStream) Close() error {
	return x.stream.Close()
}

func (x *hIStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hIStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hIStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hIStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *hIHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HIHandler.PingPong(ctx, &hIPingPongStream{stream})
}

type HI_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type hIPingPongStream struct {
	stream server.Stream
}

func (x *hIPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *hIPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hIPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hIPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hIPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *hIPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
