// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: proto/search.proto

package ser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SearchV_Search_FullMethodName = "/SearchV/Search"
)

// SearchVClient is the client API for SearchV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchVClient interface {
	Search(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type searchVClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchVClient(cc grpc.ClientConnInterface) SearchVClient {
	return &searchVClient{cc}
}

func (c *searchVClient) Search(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, SearchV_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchVServer is the server API for SearchV service.
// All implementations must embed UnimplementedSearchVServer
// for forward compatibility
type SearchVServer interface {
	Search(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedSearchVServer()
}

// UnimplementedSearchVServer must be embedded to have forward compatible implementations.
type UnimplementedSearchVServer struct {
}

func (UnimplementedSearchVServer) Search(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchVServer) mustEmbedUnimplementedSearchVServer() {}

// UnsafeSearchVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchVServer will
// result in compilation errors.
type UnsafeSearchVServer interface {
	mustEmbedUnimplementedSearchVServer()
}

func RegisterSearchVServer(s grpc.ServiceRegistrar, srv SearchVServer) {
	s.RegisterService(&SearchV_ServiceDesc, srv)
}

func _SearchV_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchVServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchV_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchVServer).Search(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchV_ServiceDesc is the grpc.ServiceDesc for SearchV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SearchV",
	HandlerType: (*SearchVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchV_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search.proto",
}
