// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: stu.proto

package ppc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reqc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Reqc) Reset() {
	*x = Reqc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reqc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reqc) ProtoMessage() {}

func (x *Reqc) ProtoReflect() protoreflect.Message {
	mi := &file_stu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reqc.ProtoReflect.Descriptor instead.
func (*Reqc) Descriptor() ([]byte, []int) {
	return file_stu_proto_rawDescGZIP(), []int{0}
}

func (x *Reqc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Resc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age string `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Resc) Reset() {
	*x = Resc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resc) ProtoMessage() {}

func (x *Resc) ProtoReflect() protoreflect.Message {
	mi := &file_stu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resc.ProtoReflect.Descriptor instead.
func (*Resc) Descriptor() ([]byte, []int) {
	return file_stu_proto_rawDescGZIP(), []int{1}
}

func (x *Resc) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

var File_stu_proto protoreflect.FileDescriptor

var file_stu_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x74, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x52,
	0x65, 0x71, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x63, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x70,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stu_proto_rawDescOnce sync.Once
	file_stu_proto_rawDescData = file_stu_proto_rawDesc
)

func file_stu_proto_rawDescGZIP() []byte {
	file_stu_proto_rawDescOnce.Do(func() {
		file_stu_proto_rawDescData = protoimpl.X.CompressGZIP(file_stu_proto_rawDescData)
	})
	return file_stu_proto_rawDescData
}

var file_stu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stu_proto_goTypes = []interface{}{
	(*Reqc)(nil), // 0: Reqc
	(*Resc)(nil), // 1: Resc
}
var file_stu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stu_proto_init() }
func file_stu_proto_init() {
	if File_stu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reqc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stu_proto_goTypes,
		DependencyIndexes: file_stu_proto_depIdxs,
		MessageInfos:      file_stu_proto_msgTypes,
	}.Build()
	File_stu_proto = out.File
	file_stu_proto_rawDesc = nil
	file_stu_proto_goTypes = nil
	file_stu_proto_depIdxs = nil
}
